export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST'
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCESS'
export const PACKAGE_LIST_FAIL = 'PACKAGE_LIST_FAIL'

export const PACKAGE_DETAILS_REQUEST = 'PACKAGE_DETAILS_REQUEST'
export const PACKAGE_DETAILS_SUCCESS = 'PACKAGE_DETAILS_SUCESS'
export const PACKAGE_DETAILS_FAIL = 'PACKAGE_DETAILS_FAIL'