# Generated by Django 5.0.1 on 2024-01-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.IntegerField(default=2000)),
                ('image', models.URLField(help_text='Fromimdb')),
                ('summary', models.TextField(help_text='shortdescription')),
                ('Rating', models.CharField(default='0/10', max_length=150)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.IntegerField(default=2000)),
                ('image', models.URLField(help_text='Fromimdb')),
                ('table_of_contents', models.TextField(help_text='shortdescription')),
                ('Rating', models.CharField(default='0/10', max_length=150)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.IntegerField(default=2000)),
                ('image', models.URLField(help_text='Fromimdb')),
                ('summary', models.TextField(help_text='shortdescription')),
                ('Rating', models.CharField(default='0/10', max_length=150)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
