# Generated by Django 5.0.1 on 2024-01-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='Rating',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='Rating',
            field=models.CharField(default='0/10', help_text='shortdescription', max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(help_text='goodreads'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='image',
            field=models.URLField(help_text='froomgoogle'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Rating',
            field=models.CharField(default='0/10', help_text='Fromimdb', max_length=150),
        ),
    ]
