# Generated by Django 5.0.1 on 2024-02-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_rename_rating_magazine_publisher_alter_book_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightsNum', models.CharField(max_length=150)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('Rating', models.CharField(default='0/10', help_text='Fromimdb', max_length=150)),
            ],
            options={
                'ordering': ['flightsNum'],
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
