# Generated by Django 5.0.1 on 2024-02-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0003_flights_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.IntegerField(default=2000)),
                ('image', models.URLField(help_text='goodreads')),
                ('summary', models.TextField(help_text='shortdescription')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Rating',
        ),
        migrations.AddField(
            model_name='packages',
            name='flights',
            field=models.ManyToManyField(related_name='packages', to='movieapi.flights'),
        ),
    ]
