# Generated by Django 5.0.1 on 2024-02-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_packages_delete_book_remove_flights_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='release_date',
            new_name='releaseDate',
        ),
    ]
