# Generated by Django 5.0.1 on 2024-02-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0005_rename_release_date_packages_releasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('OpeningDate', models.DateTimeField()),
                ('image', models.URLField(help_text='froomgoogle')),
                ('information', models.TextField(help_text='shortdescription')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Magazine',
        ),
        migrations.AlterField(
            model_name='packages',
            name='releaseDate',
            field=models.DateTimeField(),
        ),
    ]
