# Generated by Django 5.0.1 on 2024-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0006_hotels_delete_magazine_alter_packages_releasedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='shortdescription')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='arrival_time',
            new_name='arrivalTime',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='departure_time',
            new_name='departureTime',
        ),
        migrations.AddField(
            model_name='packages',
            name='hotels',
            field=models.ManyToManyField(related_name='packages', to='movieapi.hotels'),
        ),
        migrations.AddField(
            model_name='packages',
            name='type',
            field=models.BooleanField(default=False, help_text='false = premade, true = custom'),
        ),
        migrations.AddField(
            model_name='packages',
            name='activities',
            field=models.ManyToManyField(related_name='packages', to='movieapi.activities'),
        ),
    ]
