# Generated by Django 5.0.1 on 2024-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0007_activities_rename_arrival_time_flights_arrivaltime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotels',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
