# Generated by Django 5.0.2 on 2024-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_activity_flight_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
