# Generated by Django 5.0.2 on 2024-03-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_flight_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrivalTime',
            new_name='arrival',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departureTime',
            new_name='departure',
        ),
    ]
