# Generated by Django 5.0.2 on 2024-03-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_arrivaltime_flight_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='OpeningDate',
        ),
    ]
