# Generated by Django 5.0.2 on 2024-03-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_hotel_openingdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
