# Generated by Django 5.0.2 on 2024-03-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_descriptiion_hotel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='startTime',
        ),
    ]
