# Generated by Django 5.0.2 on 2024-04-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_checkoutaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='booking',
            new_name='bookingDetail',
        ),
    ]
