# Generated by Django 5.0.3 on 2024-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_flight_remove_package_activities_package_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('OpeningDate', models.DateTimeField()),
                ('descriptiion', models.TextField(help_text='shortdescription')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('room', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(related_name='package', to='base.flight'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='package',
            name='Hotel',
        ),
        migrations.AlterField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(related_name='package', to='base.activity'),
        ),
        migrations.AddField(
            model_name='package',
            name='Hotel',
            field=models.ManyToManyField(related_name='package', to='base.hotel'),
        ),
    ]
