# Generated by Django 5.0.3 on 2024-03-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_hotel_activity_image_flight_image_package_flights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='Hotel',
            field=models.ManyToManyField(related_name='packages', to='base.hotel'),
        ),
        migrations.AlterField(
            model_name='package',
            name='activities',
            field=models.ManyToManyField(related_name='packages', to='base.activity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(related_name='packages', to='base.flight'),
        ),
    ]
